// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'error.freezed.dart';

@freezed
sealed class SlimgBridgeError with _$SlimgBridgeError {
  const SlimgBridgeError._();

  const factory SlimgBridgeError.invalidRequest({required String message}) =
      SlimgBridgeError_InvalidRequest;
  const factory SlimgBridgeError.invalidPath({
    required String path,
    required String message,
  }) = SlimgBridgeError_InvalidPath;
  const factory SlimgBridgeError.unsupportedFormat({required String format}) =
      SlimgBridgeError_UnsupportedFormat;
  const factory SlimgBridgeError.unknownFormat({required String detail}) =
      SlimgBridgeError_UnknownFormat;
  const factory SlimgBridgeError.decode({required String message}) =
      SlimgBridgeError_Decode;
  const factory SlimgBridgeError.encode({required String message}) =
      SlimgBridgeError_Encode;
  const factory SlimgBridgeError.resize({required String message}) =
      SlimgBridgeError_Resize;
  const factory SlimgBridgeError.crop({required String message}) =
      SlimgBridgeError_Crop;
  const factory SlimgBridgeError.extend({required String message}) =
      SlimgBridgeError_Extend;
  const factory SlimgBridgeError.io({required String message}) =
      SlimgBridgeError_Io;
  const factory SlimgBridgeError.internal({required String message}) =
      SlimgBridgeError_Internal;
}
