// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'error.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'types.freezed.dart';

class BatchItemResult {
  final String inputPath;
  final bool success;
  final ProcessResult? result;
  final SlimgBridgeError? error;

  const BatchItemResult({
    required this.inputPath,
    required this.success,
    this.result,
    this.error,
  });

  @override
  int get hashCode =>
      inputPath.hashCode ^ success.hashCode ^ result.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BatchItemResult &&
          runtimeType == other.runtimeType &&
          inputPath == other.inputPath &&
          success == other.success &&
          result == other.result &&
          error == other.error;
}

class BatchProcessRequest {
  final List<String> inputPaths;
  final String? outputDir;
  final bool overwrite;
  final ImageOperation operation;
  final bool continueOnError;

  const BatchProcessRequest({
    required this.inputPaths,
    this.outputDir,
    required this.overwrite,
    required this.operation,
    required this.continueOnError,
  });

  @override
  int get hashCode =>
      inputPaths.hashCode ^
      outputDir.hashCode ^
      overwrite.hashCode ^
      operation.hashCode ^
      continueOnError.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BatchProcessRequest &&
          runtimeType == other.runtimeType &&
          inputPaths == other.inputPaths &&
          outputDir == other.outputDir &&
          overwrite == other.overwrite &&
          operation == other.operation &&
          continueOnError == other.continueOnError;
}

class ConvertOptions {
  final String targetFormat;
  final int quality;

  const ConvertOptions({required this.targetFormat, required this.quality});

  @override
  int get hashCode => targetFormat.hashCode ^ quality.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConvertOptions &&
          runtimeType == other.runtimeType &&
          targetFormat == other.targetFormat &&
          quality == other.quality;
}

class CropOptions {
  final CropSpec crop;
  final String? targetFormat;
  final int quality;

  const CropOptions({
    required this.crop,
    this.targetFormat,
    required this.quality,
  });

  @override
  int get hashCode => crop.hashCode ^ targetFormat.hashCode ^ quality.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CropOptions &&
          runtimeType == other.runtimeType &&
          crop == other.crop &&
          targetFormat == other.targetFormat &&
          quality == other.quality;
}

@freezed
sealed class CropSpec with _$CropSpec {
  const CropSpec._();

  const factory CropSpec.region({
    required int x,
    required int y,
    required int width,
    required int height,
  }) = CropSpec_Region;
  const factory CropSpec.aspectRatio({
    required int width,
    required int height,
  }) = CropSpec_AspectRatio;
}

class EncodedImageResult {
  final Uint8List encodedBytes;
  final String format;
  final int width;
  final int height;
  final BigInt sizeBytes;

  const EncodedImageResult({
    required this.encodedBytes,
    required this.format,
    required this.width,
    required this.height,
    required this.sizeBytes,
  });

  @override
  int get hashCode =>
      encodedBytes.hashCode ^
      format.hashCode ^
      width.hashCode ^
      height.hashCode ^
      sizeBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EncodedImageResult &&
          runtimeType == other.runtimeType &&
          encodedBytes == other.encodedBytes &&
          format == other.format &&
          width == other.width &&
          height == other.height &&
          sizeBytes == other.sizeBytes;
}

class ExtendOptions {
  final ExtendSpec extend;
  final FillSpec? fill;
  final String? targetFormat;
  final int quality;

  const ExtendOptions({
    required this.extend,
    this.fill,
    this.targetFormat,
    required this.quality,
  });

  @override
  int get hashCode =>
      extend.hashCode ^
      fill.hashCode ^
      targetFormat.hashCode ^
      quality.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExtendOptions &&
          runtimeType == other.runtimeType &&
          extend == other.extend &&
          fill == other.fill &&
          targetFormat == other.targetFormat &&
          quality == other.quality;
}

@freezed
sealed class ExtendSpec with _$ExtendSpec {
  const ExtendSpec._();

  const factory ExtendSpec.aspectRatio({
    required int width,
    required int height,
  }) = ExtendSpec_AspectRatio;
  const factory ExtendSpec.size({required int width, required int height}) =
      ExtendSpec_Size;
}

@freezed
sealed class FillSpec with _$FillSpec {
  const FillSpec._();

  const factory FillSpec.solid({
    required int r,
    required int g,
    required int b,
    required int a,
  }) = FillSpec_Solid;
  const factory FillSpec.transparent() = FillSpec_Transparent;
}

class FormatInfo {
  final String id;
  final String extension_;
  final bool canEncode;

  const FormatInfo({
    required this.id,
    required this.extension_,
    required this.canEncode,
  });

  @override
  int get hashCode => id.hashCode ^ extension_.hashCode ^ canEncode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FormatInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          extension_ == other.extension_ &&
          canEncode == other.canEncode;
}

class ImageMetadata {
  final int width;
  final int height;
  final String format;
  final BigInt? fileSize;

  const ImageMetadata({
    required this.width,
    required this.height,
    required this.format,
    this.fileSize,
  });

  @override
  int get hashCode =>
      width.hashCode ^ height.hashCode ^ format.hashCode ^ fileSize.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImageMetadata &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          format == other.format &&
          fileSize == other.fileSize;
}

@freezed
sealed class ImageOperation with _$ImageOperation {
  const ImageOperation._();

  const factory ImageOperation.convert(ConvertOptions field0) =
      ImageOperation_Convert;
  const factory ImageOperation.optimize(OptimizeOptions field0) =
      ImageOperation_Optimize;
  const factory ImageOperation.resize(ResizeOptions field0) =
      ImageOperation_Resize;
  const factory ImageOperation.crop(CropOptions field0) = ImageOperation_Crop;
  const factory ImageOperation.extend(ExtendOptions field0) =
      ImageOperation_Extend;
}

class OptimizeOptions {
  final int quality;
  final bool writeOnlyIfSmaller;

  const OptimizeOptions({
    required this.quality,
    required this.writeOnlyIfSmaller,
  });

  @override
  int get hashCode => quality.hashCode ^ writeOnlyIfSmaller.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OptimizeOptions &&
          runtimeType == other.runtimeType &&
          quality == other.quality &&
          writeOnlyIfSmaller == other.writeOnlyIfSmaller;
}

class PreviewFileRequest {
  final String inputPath;
  final ImageOperation operation;

  const PreviewFileRequest({required this.inputPath, required this.operation});

  @override
  int get hashCode => inputPath.hashCode ^ operation.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PreviewFileRequest &&
          runtimeType == other.runtimeType &&
          inputPath == other.inputPath &&
          operation == other.operation;
}

class PreviewResult {
  final Uint8List encodedBytes;
  final String format;
  final int width;
  final int height;
  final BigInt sizeBytes;

  const PreviewResult({
    required this.encodedBytes,
    required this.format,
    required this.width,
    required this.height,
    required this.sizeBytes,
  });

  @override
  int get hashCode =>
      encodedBytes.hashCode ^
      format.hashCode ^
      width.hashCode ^
      height.hashCode ^
      sizeBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PreviewResult &&
          runtimeType == other.runtimeType &&
          encodedBytes == other.encodedBytes &&
          format == other.format &&
          width == other.width &&
          height == other.height &&
          sizeBytes == other.sizeBytes;
}

class ProcessBytesRequest {
  final Uint8List data;
  final ImageOperation operation;

  const ProcessBytesRequest({required this.data, required this.operation});

  @override
  int get hashCode => data.hashCode ^ operation.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProcessBytesRequest &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          operation == other.operation;
}

class ProcessFileBatchRequest {
  final List<ProcessFileRequest> requests;
  final bool continueOnError;

  const ProcessFileBatchRequest({
    required this.requests,
    required this.continueOnError,
  });

  @override
  int get hashCode => requests.hashCode ^ continueOnError.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProcessFileBatchRequest &&
          runtimeType == other.runtimeType &&
          requests == other.requests &&
          continueOnError == other.continueOnError;
}

class ProcessFileRequest {
  final String inputPath;
  final String? outputPath;
  final bool overwrite;
  final ImageOperation operation;

  const ProcessFileRequest({
    required this.inputPath,
    this.outputPath,
    required this.overwrite,
    required this.operation,
  });

  @override
  int get hashCode =>
      inputPath.hashCode ^
      outputPath.hashCode ^
      overwrite.hashCode ^
      operation.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProcessFileRequest &&
          runtimeType == other.runtimeType &&
          inputPath == other.inputPath &&
          outputPath == other.outputPath &&
          overwrite == other.overwrite &&
          operation == other.operation;
}

class ProcessResult {
  final String outputPath;
  final String format;
  final int width;
  final int height;
  final BigInt originalSize;
  final BigInt newSize;
  final bool didWrite;

  const ProcessResult({
    required this.outputPath,
    required this.format,
    required this.width,
    required this.height,
    required this.originalSize,
    required this.newSize,
    required this.didWrite,
  });

  @override
  int get hashCode =>
      outputPath.hashCode ^
      format.hashCode ^
      width.hashCode ^
      height.hashCode ^
      originalSize.hashCode ^
      newSize.hashCode ^
      didWrite.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProcessResult &&
          runtimeType == other.runtimeType &&
          outputPath == other.outputPath &&
          format == other.format &&
          width == other.width &&
          height == other.height &&
          originalSize == other.originalSize &&
          newSize == other.newSize &&
          didWrite == other.didWrite;
}

class ResizeOptions {
  final ResizeSpec resize;
  final String? targetFormat;
  final int quality;

  const ResizeOptions({
    required this.resize,
    this.targetFormat,
    required this.quality,
  });

  @override
  int get hashCode =>
      resize.hashCode ^ targetFormat.hashCode ^ quality.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ResizeOptions &&
          runtimeType == other.runtimeType &&
          resize == other.resize &&
          targetFormat == other.targetFormat &&
          quality == other.quality;
}

@freezed
sealed class ResizeSpec with _$ResizeSpec {
  const ResizeSpec._();

  const factory ResizeSpec.width({required int value}) = ResizeSpec_Width;
  const factory ResizeSpec.height({required int value}) = ResizeSpec_Height;
  const factory ResizeSpec.exact({required int width, required int height}) =
      ResizeSpec_Exact;
  const factory ResizeSpec.fit({
    required int maxWidth,
    required int maxHeight,
  }) = ResizeSpec_Fit;
  const factory ResizeSpec.scale({required double factor}) = ResizeSpec_Scale;
}
