[package]
name = "oimg_rust"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
anyhow = "1.0.100"
dify = "0.8.0"
fast-ssim2 = { version = "0.7.1", features = ["rayon"] }
flutter_rust_bridge = "=2.11.1"
image = { version = "0.25.2", default-features = false }
imagesize = { version = "0.15.0", default-features = false, features = ["heif", "jpeg", "jxl", "png", "qoi", "webp"] }
img-parts = "0.4.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
slimg-core = { path = "../../slimg/crates/slimg-core", default-features = false, features = ["pngquant", "jpeg-backend-jpegli"] }
slimg-exec = { path = "../../slimg/crates/slimg-exec", default-features = false, features = ["jpeg-backend-jpegli"] }
tempfile = "3.23.0"
thiserror = "2.0.17"
tjdistler-iqa = { path = "../../tjdistler-iqa-fork" }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }

[dev-dependencies]
tempfile = "3.23.0"
