// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../error.dart';
import '../frb_generated.dart';
import '../types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `with_internal`

String version() => RustLib.instance.api.crateApiBridgeVersion();

List<FormatInfo> supportedFormats() =>
    RustLib.instance.api.crateApiBridgeSupportedFormats();

void setTimingLogsEnabled({required bool enabled}) =>
    RustLib.instance.api.crateApiBridgeSetTimingLogsEnabled(enabled: enabled);

Future<ImageMetadata> inspectFile({required String inputPath}) =>
    RustLib.instance.api.crateApiBridgeInspectFile(inputPath: inputPath);

Future<ImageMetadata> inspectBytes({required List<int> data}) =>
    RustLib.instance.api.crateApiBridgeInspectBytes(data: data);

Future<PreviewResult> previewFile({required PreviewFileRequest request}) =>
    RustLib.instance.api.crateApiBridgePreviewFile(request: request);

Future<double?> computePreviewPixelMatchPercentage({
  required PreviewQualityMetricsRequest request,
}) => RustLib.instance.api.crateApiBridgeComputePreviewPixelMatchPercentage(
  request: request,
);

Future<double?> computePreviewMsSsim({
  required PreviewQualityMetricsRequest request,
}) => RustLib.instance.api.crateApiBridgeComputePreviewMsSsim(request: request);

Future<double?> computePreviewSsimulacra2({
  required PreviewQualityMetricsRequest request,
}) => RustLib.instance.api.crateApiBridgeComputePreviewSsimulacra2(
  request: request,
);

Future<EncodedImageResult?> computePreviewDifferenceImage({
  required PreviewQualityMetricsRequest request,
}) => RustLib.instance.api.crateApiBridgeComputePreviewDifferenceImage(
  request: request,
);

Future<ProcessResult> processFile({required ProcessFileRequest request}) =>
    RustLib.instance.api.crateApiBridgeProcessFile(request: request);

Future<EncodedImageResult> processBytes({
  required ProcessBytesRequest request,
}) => RustLib.instance.api.crateApiBridgeProcessBytes(request: request);

Future<List<BatchItemResult>> processFiles({
  required BatchProcessRequest request,
}) => RustLib.instance.api.crateApiBridgeProcessFiles(request: request);

Future<List<BatchItemResult>> processFileBatch({
  required ProcessFileBatchRequest request,
}) => RustLib.instance.api.crateApiBridgeProcessFileBatch(request: request);

Future<BatchJobHandle> startProcessFileBatchJob({
  required ProcessFileBatchRequest request,
}) => RustLib.instance.api.crateApiBridgeStartProcessFileBatchJob(
  request: request,
);

Future<BatchJobSnapshot> getProcessFileBatchJob({required String jobId}) =>
    RustLib.instance.api.crateApiBridgeGetProcessFileBatchJob(jobId: jobId);

Future<void> cancelProcessFileBatchJob({required String jobId}) =>
    RustLib.instance.api.crateApiBridgeCancelProcessFileBatchJob(jobId: jobId);

Future<void> disposeProcessFileBatchJob({required String jobId}) =>
    RustLib.instance.api.crateApiBridgeDisposeProcessFileBatchJob(jobId: jobId);
